replicaCount: 1

image:
  repository: soundmastery-client-local # use minikibe image load to copy images from local docker
  pullPolicy: Never
  tag: "latest"

imagePullSecrets: []
nameOverride: "soundmastery-client"
fullnameOverride: "soundmastery-client"

serviceAccount:
  create: true
  name: "soundmastery-client"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: soundmastery-client.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false