// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundMastery.DataAccess.Contexts;

#nullable disable

namespace SoundMastery.Migration.Migrations
{
    [DbContext(typeof(SoundMasteryContext))]
    [Migration("20230902162627_RemoveProductFromCourse")]
    partial class RemoveProductFromCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SoundMastery")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoundMastery.Domain.Core.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FinishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseLesson", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonAttendee", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CourseLessonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseLessonId");

                    b.HasIndex("CourseLessonId");

                    b.ToTable("CourseLessonAttendee", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonHomeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseLessonId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CourseLessonId");

                    b.ToTable("CourseLessonHomeAssignment", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonHomeAssignmentMaterial", b =>
                {
                    b.Property<int>("CourseHomeAssignmentId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("CourseHomeAssignmentId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("CourseLessonHomeAssignmentMaterial", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonMaterial", b =>
                {
                    b.Property<int>("CourseLessonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("CourseLessonId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("CourseLessonMaterial", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseParticipant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseParticipant", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.FollowingStudent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("FollowingStudent", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualHomeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IndividualLessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndividualLessonId")
                        .IsUnique();

                    b.ToTable("IndividualHomeAssignment", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("IndividualLesson", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLessonHomeAssignmentMaterial", b =>
                {
                    b.Property<int>("IndividualHomeAssignmentId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("IndividualHomeAssignmentId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("IndividualLessonHomeAssignmentMaterial", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLessonMaterial", b =>
                {
                    b.Property<int>("IndividualLessonId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("IndividualLessonId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("IndividualLessonMaterial", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Material", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Products", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Roles", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "SoundMastery");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.Course", b =>
                {
                    b.HasOne("SoundMastery.Domain.Identity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLesson", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonAttendee", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.CourseLesson", "CourseLesson")
                        .WithMany("Attendees")
                        .HasForeignKey("CourseLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseLesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonHomeAssignment", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.CourseLesson", "CourseLesson")
                        .WithMany()
                        .HasForeignKey("CourseLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLesson");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonHomeAssignmentMaterial", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.CourseLessonHomeAssignment", "CourseLessonHomeAssignment")
                        .WithMany("Materials")
                        .HasForeignKey("CourseHomeAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Core.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLessonHomeAssignment");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonMaterial", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.CourseLesson", "CourseLesson")
                        .WithMany("Materials")
                        .HasForeignKey("CourseLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Core.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLesson");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseParticipant", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.Course", "Course")
                        .WithMany("Participants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.FollowingStudent", b =>
                {
                    b.HasOne("SoundMastery.Domain.Identity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "User")
                        .WithMany("FollowingStudents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualHomeAssignment", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.IndividualLesson", "IndividualLesson")
                        .WithOne("HomeAssignment")
                        .HasForeignKey("SoundMastery.Domain.Core.IndividualHomeAssignment", "IndividualLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualLesson");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLesson", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Identity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLessonHomeAssignmentMaterial", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.IndividualHomeAssignment", "IndividualHomeAssignment")
                        .WithMany("Materials")
                        .HasForeignKey("IndividualHomeAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Core.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualHomeAssignment");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLessonMaterial", b =>
                {
                    b.HasOne("SoundMastery.Domain.Core.IndividualLesson", "IndividualLesson")
                        .WithMany("Materials")
                        .HasForeignKey("IndividualLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundMastery.Domain.Core.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualLesson");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("SoundMastery.Domain.Identity.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.Role", b =>
                {
                    b.HasOne("SoundMastery.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLesson", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.CourseLessonHomeAssignment", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualHomeAssignment", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("SoundMastery.Domain.Core.IndividualLesson", b =>
                {
                    b.Navigation("HomeAssignment");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("SoundMastery.Domain.Identity.User", b =>
                {
                    b.Navigation("FollowingStudents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
