version: "3.8"

services:
  api:
    image: docker.pkg.github.com/arublevsky/soundmastery/sound-mastery-api:${APP_VERSION:?err}
    build:
      context: ./../../src/server 
    ports:
      - '${API_PORT?err}:80'
    volumes:
      - ./app/api/Logs:/app/api/Logs
    environment:
        - ASPNETCORE_ENVIRONMENT=Production  
        - DB_COMMAND=${DB_COMMAND?err}
  client:
    image: docker.pkg.github.com/arublevsky/soundmastery/sound-mastery-client:${APP_VERSION:?err}
    build:
      context: ./../../src/client
    ports:
      - '${CLIENT_PORT?err}:80'
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root   
    environment:
      SA_PASSWORD: ${SA_PASSWORD?err}
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    ports:
      - '1433:1433'
    expose:
      - 1433