# CI images build configuration
version: "3.8"

services:
  api:
    image: ghcr.io/arublevsky/sound-mastery-api:${APP_VERSION:?err}
    build:
      context: ./../../src/server  
  client:
    image: ghcr.io/arublevsky/sound-mastery-client:${APP_VERSION:?err}
    build:
      context: ./../../src/client
      dockerfile: Dockerfile-ci