version: "3.8"

services:
  api:
    image: docker.pkg.github.com/arublevsky/soundmastery/sound-mastery-api:${APP_VERSION:?err}
    build:
      context: ./../../src/server 
    ports:
      - '${API_PORT?err}:80'
    volumes:
      - ./app/api/Logs:/app/api/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - DB_COMMAND=${DB_COMMAND?err}
  client:
    image: docker.pkg.github.com/arublevsky/soundmastery/sound-mastery-client:${APP_VERSION:?err}
    build:
      context: ./../../src/client
    ports:
      - '${CLIENT_PORT?err}:80'
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SA_PASSWORD?err}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432