name: AzureDeploy

on:
  pull_request:
    branches: [develop]
    types: [labeled]
jobs:
  azure-pr-deploy:
    name: Deploy PR package
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'azure-deploy-pull-request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        env:
          CREDENTIALS: ${{ secrets.AZURE_AUTH }}
        with:
          creds: ${{ env.CREDENTIALS }}
      
      - name: Set app version
        id: get_version
        run: |
          ./build.sh --target SetAppVersion
          echo "::set-output name=app-version::$(grep APP_VERSION ./.config/ci.env | cut -d '=' -f 2)"

      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_AUTH }}'
          cluster-name: SoundMasteryCluster
          resource-group: SoundMasteryCluster_group

      - uses: Azure/k8s-create-secret@v1.1
        with:
          namespace: ${{ env.NAMESPACE  }}
          container-registry-url: ghcr.io
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.CR_PAT }}
          secret-name: demo-k8s-secret

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './tools/helm/postgres'
          helm-version: 'latest'
        id: bake-postgres

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './tools/helm/backend'
          overrideFiles: './tools/helm/backend/values.yaml'
          overrides: |
            replicas:2
            image.repository:ghcr.io/arublevsky/sound-mastery-api
            image.pullPolicy:Always
            image.tag:${{ steps.get_version.outputs.app-version }}
          helm-version: 'latest'
        id: bake-backend

      - uses: azure/k8s-bake@v2
        with:
          renderEngine: 'helm'
          helmChart: './tools/helm/client'
          overrideFiles: './tools/helm/client/values.yaml'
          overrides: |
            image.repository:ghcr.io/arublevsky/sound-mastery-client
            image.pullPolicy:Always
            image.tag:${{ steps.get_version.outputs.app-version }}
            ingress.annotations.kubernetes\.io/ingress\.class: azure/application-gateway
            ingres.hosts[0].host:soundmasterycluster-dns-h0lwk2ab.hcp.westus.azmk8s.io
          helm-version: 'latest'
        id: bake-client

      - uses: Azure/k8s-deploy@v1.2
        with:
          action: deploy
          manifests: ${{ steps.bake-postgres.outputs.manifestsBundle }}
          imagepullsecrets: |
              demo-k8s-secret

      - uses: Azure/k8s-deploy@v1.2
        with:
          action: deploy
          manifests: ${{ steps.bake-backend.outputs.manifestsBundle }}
          imagepullsecrets: |
              demo-k8s-secret

      - uses: Azure/k8s-deploy@v1.2
        with:
          action: deploy
          manifests: ${{ steps.bake-client.outputs.manifestsBundle }}
          imagepullsecrets: |
              demo-k8s-secret