name: CI

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: RunBuild 
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: ./artifacts
          retention-days: 5

      - name: Coverage report 
        uses: 5monkeys/cobertura-action@master
        with:
          path: ./artifacts/coverage/coverage.cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 50
          show_line: true
          show_branch: true
          show_class_names: true
          only_changed_files: true

  push_images:
    needs: build
    name: Publish Docker images
    runs-on: ubuntu-latest
    steps:
      - ​uses​: ​docker/login-action@v2
  ​      ​with​: 
  ​        ​registry​: ​ghcr.io
  ​        ​username​: ${{ github.actor }}
  ​        ​password​: ${{ secrets.CR_PAT }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Docker images
        run: ./build.sh --target PublishImages
