name: CI

on:
  pull_request:
    branches: [ develop, master ]

  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: RunBuild 
        run: ./build.sh

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: ./artifacts
          retention-days: 5
      - name: Coverage report 
          uses: 5monkeys/cobertura-action@master
          with:
            path: ./artifacts/coverage/coverage.cobertura.xml
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            minimum_coverage: 50

  push_images:
    needs: build
    name: Publish Docker images
    runs-on: ubuntu-latest
    env:
      DB_COMMAND: update
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Docker images
        run: ./build.sh --target PublishImages

  push_images_release:
    name: Publish Docker images (release)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    env:
      DB_COMMAND: update
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Docker images  (release)
        run: ./build.sh --target PublishImages