name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: RunBuild 
        run: ./build.sh

  push_to_registry:
    needs: build
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    env:
      DB_COMMAND: recreate
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Push Docker images to GitHub Packages
        run: |
          chmod +x ./push-to-registry.sh
          ./push-to-registry.sh