name: Release

on:
  release:
    types:
      - created
jobs:
  push_images_release:
    name: Publish Release Docker images
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Publish Docker images
        run: ./build.sh --target PublishImages